from freelanceapp.models import SkillSet

skill_list  = ['Accounting',
'Administrative / Secretarial',
'Advertising',
'Arabic',
'Architect',
'Automotive',
'Banking',
'Beautician',
'Bookkeeping',
'Business Analyst',
'Business Development',
'Business Intelligence',
'Business Manager',
'Cashier',
'Chef',
'College Admissions',
'Communications',
'Computer Programming',
'Computer Repair',
'Construction',
'Counseling',
'Consulting',
'Customer Service',
'Data Scientist',
'Dietician / Nutritionist',
'Editing',
'English',
'Event Management',
'Executive Assistant',
'Engineering',
'Fashion Design',
'Finance',
'Financial Advisor / Planner',
'French',
'German',
'Graphic Design',
'Healthcare / Hospital Administration',
'Human Resources',
'Inside Sales',
'Insurance',
'Interior Design',
'Information Technology',
'IT Soft Skills',
'Law Enforcement Skills',
'Leadership',
'Legal',
'Maintenance and Janitorial',
'Management',
'Marketing',
'Office Assistant',
'Office Manager',
'Paralegal / Legal Assistant',
'Personal Assistant',
'Personal Development',
'Personal Trainer',
'Photography',
'Portuguese',
'Physical Therapist',
'Physician Assistant',
'Product Manager',
'Project Manager',
'Public Relations',
'Public Speaking',
'Real Estate',
'Research Assistant',
'Retail',
'Restaurant and Food Service',
'Sales',
'Social Entrepreneurship',
'Social Media',
'Social Work',
'Spanish',
'Strategy',
'Teaching',
'Television / Film Producer',
'Translation',
'Video Editing',
'Web Design',
'Writing']

def create_base_skills(skill_list=skill_list):
	for skill in skill_list:
		try:
			new_skillset = SkillSet(value = skill.lower())
			new_skillset.save()
		except:
			pass
	return True
